// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqedtdbwjibizylpqjao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZWR0ZGJ3amliaXp5bHBxamFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTMyMTEsImV4cCI6MjA3MTA4OTIxMX0.mQ4BC4M6CoATXFiO2Ah_jJ0D5u8l2ulupRAt6ufJ92s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});